# Generated by Django 5.1.7 on 2025-03-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_images/')),
                ('overview', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
