# Generated by Django 5.1.7 on 2025-03-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='course_images/')),
                ('file', models.FileField(upload_to='course_files/')),
            ],
        ),
    ]
