# Generated by Django 5.1.6 on 2025-03-09 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Messaging', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Messaging.session'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Messaging.session'),
        ),
    ]
