# Generated by Django 5.1.7 on 2025-03-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
